spring.application.name=ElectricityBilling
spring.datasource.url=jdbc:mysql://localhost:3306/electricity_db
spring.datasource.username=root
spring.datasource.password=mahi007@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true